# Generated by Django 6.0 on 2025-12-06 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_appointmentslot_cancel_request_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='doctor_google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='patient_google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
