# Generated by Django 6.0 on 2025-12-05 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_doctorpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentslot',
            name='cancel_request_by',
            field=models.CharField(blank=True, choices=[('doctor', 'Doctor'), ('patient', 'Patient')], max_length=10, null=True),
        ),
    ]
